### ISSUE TITLE
Ame spritesheet license

### ISSUE THREAD

**Issue by bela333** [walfie/ame-cubes#1]
Hello!

I would like to use the Ame sprites in a personal project. I couldn't find any license for the asset so I assumed it is also under MIT. Understandably that felt weird so I thought I should ask to make sure.

Thank you

**Comment by walfie** [comment]
In general, feel free to use my art for any non-commercial purposes (credit is appreciated, but not required)

**Comment by bela333** [comment]
Got it, thanks!
